#!/usr/bin/env bash
# This script displays "Best School" 10 times using "while" loop but on after the 9th iteration, "Hi" is displayed then "Best School"

i=0
while [ $i -lt 10 ]
do
    echo "Best School"

    if [ $i -eq 8 ];
    then
        echo "Hi"
    fi
    ((i++))
done
